<?php

namespace Database\Seeders\Courses;

use App\Models\Course\Template;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TemplatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $records = [
        ['name' => ' حلقة نقاش حول مسرعة الاعلام السعودي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' حلقة نقاش افتراضية الإعلام الرياضي .. مواجهات دون تفويض', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' حفل تدشين برامج وفعاليات بيت شباب الأحساء الإعلامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' كيف نكون فاعلين في تويتر ـ حفرالباطن', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التنظيم القانوني للنشر الإعلامي وحقوق الإنسان في السعودية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' كورونا والاعلام السعودي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' دور الإعلام أثناء الأزمات و الحروب', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام السعودي والاقتصاد النفطي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الأحساء .. إنجازات وتطلعات وطن ال 90', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' صناعة المحتوى الإعلامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' محمية بحيرة الأصفر " مستقبل السياحة البيئية الواعد بالمملكة "', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' إعداد التقارير الإعلامية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام بين التقليد و التجديد من التراث و العمارة الإسلامية في الأحساء', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' إنتاج الفديو الصحفي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أساسيات التصوير بالجوال', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' فن المراسم و البروتوكول في العلاقات العامة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أساسيات الفوتوشوب', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مستقبل الإعلام', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أساسيات التصوير الضوئي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التعليق الصوتي .. صوتك يعبر عنك', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التدريب العملي لطالبات الاعلام في جامعة الملك فيصل', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تصوير المنتجات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' توثيق حياة الناس', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' برنامج صناعة المحتوى الإعلامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الملكية الفكرية في المملكة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التعليق الرياضي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أطلق صوتك', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تصميم الأنفوجرافيك', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' صناعة المحتوى عبر الهواتف الذكية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مهارات المتحدث الإعلامي الرسمي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الخيل بين الجمال ولحظة الالتقاط', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' فن التحرير الإعلامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' نقاط حول تصوير الفديو', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' صناعة  المحتوى الإبداعي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الصحفي الشامل', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الزاوية الأخيرة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' نجوم الزاوية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تصوير الطبيعة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' المونتاج باستخدام Adobe Premiere', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الشمس جاذبية وجمال', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التصوير الفوتوغرافي الرياضي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تصوير الزواجات و المناسبات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام وحواضر الأحساء', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' المهارات القانونية في صياغة الخبر الصحفي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' فن الإلقاء', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام السياحي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' إدارة منصات مواقع التواصل وصناعة المحتوى', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الصحافة بين المؤسسة والفرد ـ حفرالباطن', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مهارة التصوير بالجوال', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' هواة الإعلام', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التصوير بالجوال', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تدشين منصة الإعلام التطوعي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' اليوم الوطني 91 .. إحتفاء بالوحدة .. شواهد المكتسبات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' عبقرية المؤسس أبهرت العالم', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مهارات كتابة الخبر الصحفي الرياضي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تصوير المايكرو', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تأثير وسائل الإعلام في جذب الإستثمارات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' بورتورية الأطفال', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أخلاقيات الإعلام', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' حفل تدشين الصالون الاعلامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' توقيع كتاب " عاشوا في ذاكرتي "', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' صحافة الفيديو', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الأستاذ قاسم الشافعي ضيف الصالون الاعلامي بالأحساء', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الملك سلمان بن عبدالعزيز .. عهد الوثبات الخلاقة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام .. دراسة و موهبة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' زيارة الفريق التطوعي للمتحف الوطني', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' إعلام التنية وتنمية الإعلام', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التعريف باللائحة الاساسية لهيئة الصحفيين السعوديين', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التدريب الميداني لطلاب الاداب في جامعة الملك فيصل 2021', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' فن الإلقاء', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الصالون الاعلامي - رحلة مع مؤسس صحافة التلفزيون بالشرقية أ.خالد الجناحي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' معايير الإعلام المؤثر', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الجودة الإعلامية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' ورشة عمل صحافة الموبايل ـ حفرالباطن', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' اللقاء الأخوي الترفيهي الشتوي لأسرة هيئة الصحفيين بالأحساء', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أساسيات كتابة الخبر الصحفي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أساسيات التصوير الاحترافي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تجربتي في الاعلام نجران', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' اعداد وتقديم البرامج الاذاعية و التلفزيونية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' اساسيات التصوير الضوئي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أساسيات التصوير الرياضي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مهارات الكتابة الصحفية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام الإنساني الميداني', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الصالون الاعلامي يستضيف : جايع الاهداف .. 13 عام تحت الأضواء', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' 3 قرون من المجد', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' يوم التأسيس - أبرز منجزات المؤسس الإمام محمد بن سعود', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' دور الإعلام في تحجيم الشائعات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' كتابة النص الدرامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الدورة التدريبية تصميم المجوهرات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التصوير الضوئي لفريق نبض التطوعي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الممارسات المتاحة للصحفي للوصول بفعالية للجمهور', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' صحافة الموبايل في جازان', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الصالون الاعلامي .. دردرشة مع اللواء ركن متقاعد احمد الفيفي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' العلاقات العامة و الإعلام الجديد', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' فن كتابة الخبر الصحفي - نجران', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام و السياحة -- تمكين السياحة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أخلاقيات الإعلام الرقمي .. الأحساء', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الرياضة النسائية بالمنطقة وفق رؤية 2030', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام و هوية الإعلامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مهارات التصوير بالجوال - تبوك', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مهارات التصوير بالجوال - تبوك - فتيات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الحسين و الفايز يرويان تجاربهم في الصالون الاعلامي بالقصيم', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإتجاهات الحديثة للعلاقات العامة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' د.العبدالعال .. 20 عام في التوثيق السياحي الإفتراضي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' اللقاء الأخوي الرمضاني الإعلامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مهارات صناعة المحتوى بالموبايل', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تجربتي في التصوير', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' رؤية 2030 .. عنوان كبير لحاضر زاهر و مستقبل واعد', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' هيئة تطوير الأحساء .. تأهيل المكان لجودة حياة الانسان', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإنحياز و الموضوعية في التقديم', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' أهمية الحفاظ على التراث العمراني', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الأديب الشيخ عبدالله بن إدريس .. الذكرى و الذاكرة', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' التحرير الصحفي ـ فرع حفرالباطن', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مخاطر الجرائم الإلكترونية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' إضاءة LED', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' ضوابط النشر الإلكتروني ـ حفرالباطن', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' كتابة الخبر الصحفي بجازان', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تجارب شبابية ابداعية 14', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' فن التصوير الاحترافي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإلقاء .. نظريات و تطبيقات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' صحافة الموبايل بجازان', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' العلاقات العامة و الأزمات', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' إدارة الأزمات الإعلامية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام و التنمية في ظل رؤية 2030', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' صناعة المحتوى الإعلامي بجازان', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' البداية الصحيحة للصحفي الناشئ', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' إلتزامات و حقوق مهنة الصحافة والصحفيين', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الذكاء العاطفي الإعلامي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' تجربتي في الصحافة الثقافية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام عبر التواصل الإجتماعي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' إعداد البرامج التلفزيونية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مهارات الاتصال', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الاستثمار في الإعلام', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام و الإقتصاد', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الأساليب الحديثة في الترويج التجاري والإستثماري', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' مقدمة عن الملكية الفكرية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام الاقتصادي ودوره الهام في رؤية 203', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' صحافة الموبايل - تبوك', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' البرنامج الصيفي اعلاميو الغد', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإعلام السياحي و التنمية السياحية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الاسعافات الأولية', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
        ['name' => ' الإبتزاز العاطفي و وسائل التواصل الإجتماعي', 'file' => 'lorem.pdf', 'language' => 0, 'layout' => 0],
      ];

      collect($records)->each(function( $record ) {
        Template::create($record);
      });

    }
}
